FROM python:3.12-slim
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
ENV ENV_FILE=/app/.env
EXPOSE 5000
# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]